### ISSUE TITLE
你好 运行代码时候  出现报错 请求您的帮助 

### ISSUE THREAD

**Issue by lkx971216** [Zeyu-Zhu/TFDSUNet#1]
运行test_uncertainty.py 时，出现如下的报错：
100%|██████████| 1/1 [00:00<00:00,  5.40it/s]
  0%|          | 0/1088 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:/2023.6.5/TFDSUNet-main/TFDSUNet-main/test_uncertainty.py", line 85, in <module>
    MAE, RMSE = Test(test_loder, model, exp_path, 'Result')
  File "D:/2023.6.5/TFDSUNet-main/TFDSUNet-main/test_uncertainty.py", line 21, in Test
    gamma, nu, alpha, beta = model.forward(x)
  File "D:\2023.6.5\TFDSUNet-main\TFDSUNet-main\model\sffnet.py", line 116, in forward
    feature = self.SFFBlock(x)
  File "D:\ProgramData\Anaconda3\envs\TFDSUNet\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\TFDSUNet\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "D:\ProgramData\Anaconda3\envs\TFDSUNet\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\2023.6.5\TFDSUNet-main\TFDSUNet-main\model\sffnet.py", line 88, in forward
    if self.sf is True:
  File "D:\ProgramData\Anaconda3\envs\TFDSUNet\lib\site-packages\torch\nn\modules\module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SFFBlock' object has no attribute 'sf' 

运行sffnet.py时，出现如下报错：
Traceback (most recent call last):
  File "D:/2023.6.5/TFDSUNet-main/TFDSUNet-main/model/sffnet.py", line 148, in <module>
    model = SFFNet(block_num, feature_num, window_size, mid_channel_list, spa_ks_list, fre_ks_list, fus_ks_list)
  File "D:/2023.6.5/TFDSUNet-main/TFDSUNet-main/model/sffnet.py", line 129, in __init__
    self.SFFBlock.add_module('SFFBlock'+str(i), SFFBlock(window_size, feature_num, mid_channel_list[i], spa_ks_list[i], fre_ks_list[i], fus_ks_list[i], 2))
TypeError: __init__() missing 3 required positional arguments: 'fb', 'sf', and 'ff'

请问这要怎么处理？

**Comment by Zeyu-Zhu** [comment]
Thanks for your attention to our newest work. Next, I will give you some guidance on the two problems.

First, the reason why the error in 'test_uncertainty.py' happens is that we modified the 'sffnet.py' to conduct the ablation experiment, and the model we provide is trained using the old version of 'sffnet.py'. As a result, it will raise errors when you try to test the model using the new version of 'sffnet.py'. So you may train the model by yourselves and test it or if it's needed I can offer you the old version (but it will take some time).

Second, we do find the definition in 'if __name__ == '__main__':' of 'sffnet.py' is incorrect, so we have updated the right version and you may try again. 

Thank you for submitting the issue, which helps us make our code repository better. If any problems you get into about running our codes, feel free to bring up an issue again.

**Comment by lkx971216** [comment]
好的   谢谢您的回答 我已经解决问题了
